no longer need ESSID and WPA_PASSPHRASE if wpa_supplicant is set up according to README. shellcheck fixes

diff --git a/bin/compute-install b/bin/compute-install
--- a/bin/compute-install
+++ b/bin/compute-install
@@ -11,10 +11,14 @@ if [[ "${2}" == "" ]]; then
     echo "Usage is: ${0} CONTROL_NODE_IP INTERFACE_NAME [ESSID WPA_PASSPHRASE]"
     exit 1
 fi
-if [[ "${3}" != "" ]] && [[ "${4}" == "" ]]; then
-    echo "error: ESSID specified without WPA passphrase"
-    echo "Usage is: ${0} CONTROL_NODE_IP INTERFACE_NAME [ESSID WPA_PASSPHRASE]"
-    exit 1
+if [[ -e "/etc/wpa_supplicant/w.conf" ]]; then
+    WPACONF="/etc/wpa_supplicant/w.conf"
+else
+    if [[ "${3}" != "" ]] && [[ "${4}" == "" ]]; then
+        echo "error: ESSID specified without WPA passphrase"
+        echo "Usage is: ${0} CONTROL_NODE_IP INTERFACE_NAME [ESSID WPA_PASSPHRASE]"
+        exit 1
+    fi
 fi
 
 CONTROLLER="${1}"
@@ -40,8 +44,8 @@ The system time (hardware clock) needs to be set to UTC. The present
 time, according to the system clock, is:
 
 EOF
-$(date '+$F $T')
-UTC=affirmative("Is this correct")
+date '+%F %T'
+UTC=affirmative "Is this correct"
 if [[ "${UTC}" == "false" ]]; then
     echo "Please reboot and set the hardware clock."
     echo
@@ -121,6 +125,7 @@ CONTROLLER="${CONTROLLER}"
 USERIFACE="${USERIFACE}"
 USERESSID="${USERESSID}"
 USERWPAPW="${USERWPAPW}"
+WPACONF="${WPACONF}"
 # fetch util funcs
 if [[ ! -e "util.sh" ]]; then
     curl --connect-timeout 10 -s -O "\${CONTROLLER}/util.sh"
@@ -168,11 +173,15 @@ EOF2
 for dns in \${USERDNS}; do
     echo "DNS=\${dns}" >> /etc/systemd/network/20-wired.network
 done
-# if we have an essid, then all this needs to be wireless
-if [[ "\${USERESSID}" != "" ]]; then
+# if we have a wpa file or essid, then all this needs to be wireless
+if [[ "\${WPACONF}" != "" ]] || [[ "\${USERESSID}" != "" ]]; then
     mkdir -p /etc/wpa_supplicant
     mv /etc/systemd/network/20-wired.network /etc/systemd/network/25-wireless.network
-    /usr/bin/wpa_passphrase "\${USERESSID}" "\${USERWPAPW}" > /etc/wpa_supplicant/wpa_supplicant-\${USERIFACE}.conf
+    if [[ "\${WPACONF}" != "" ]]; then
+        mv "\${WPACONF}" /etc/wpa_supplicant/wpa_supplicant-\${USERIFACE}.conf
+    else
+        /usr/bin/wpa_passphrase "\${USERESSID}" "\${USERWPAPW}" > /etc/wpa_supplicant/wpa_supplicant-\${USERIFACE}.conf
+    fi
     systemctl enable wpa_supplicant@\${USERIFACE}.service
 fi
 # turn on networking
