compute-setup needs CONTROLLER

diff --git a/bin/compute-setup b/bin/compute-setup
--- a/bin/compute-setup
+++ b/bin/compute-setup
@@ -1,5 +1,13 @@
 #!/bin/bash
 set -e
+cd /root
+
+if [[ "${1}" == "" ]]; then
+    echo "error: no control node IP specified"
+    echo "Usage is: ${0} CONTROL_NODE_IP INTERFACE_NAME [ESSID WPA_PASSPHRASE]"
+    exit 1
+fi
+CONTROLLER="${1}"
 
 # source util funcs
 . ./util.sh
@@ -18,7 +26,6 @@ pip3 install ansible
 
 # create user, set passwd, config sudo access, and setup ssh keys
 shownotice "Creating user for Ansible"
-sleep 1
 useradd -d /home/farmer -m -s /bin/bash farmer
 passwd=$( openssl passwd -1 -salt BOINC "$(openssl rand -base64 32)" )
 usermod -p "${passwd}" farmer
