updated dockerfile; working on node setup/install

diff --git a/bin/node-setup b/bin/node-setup
--- a/bin/node-setup
+++ b/bin/node-setup
@@ -2,8 +2,26 @@
 set -e
 cd /root
 
-# source util funcs
+if [[ "${1}" == "" ]]; then
+    echo "error: no control node IP specified"
+    echo "Usage is: ${0} CONTROL_NODE_IP INTERFACE_NAME [ESSID WPA_PASSPHRASE]"
+    exit 1
+fi
+
+CONTROLLER="${1}"
+
+# fetch util funcs
+if [[ ! -e "common.sh" ]]; then
+    if ! curl --connect-timeout 10 -s -O "${1}/common.sh"; then
+        echo "error: can't reach control node"
+        echo "was given ip '${CONTROLLER}' -- please double check and/or check network connectivity"
+        exit 1
+    fi
+fi
+# and source
 . ./common.sh
+
+curl --connect-timeout 10 -s -O "\${CONTROLLER}/id_farmer.pub"
 
 # install preqs
 clear
